### ISSUE TITLE
Error trying to configure a new env(RPA installed on OCP)

### ISSUE THREAD

**Issue by carolagirolami** [IBM/ibm-rpa-cli#41]
### Describe the bug

Hello,
I get an error trying to configure a new environment.
See Logs for details.
Thanks

### Logs

```Shell
C:\Users\Administrator\AppData\Local\Joba\rpa cli>rpa --version
1.0.0-beta-2

C:\Users\Administrator\AppData\Local\Joba\rpa cli>rpa env new rpaDev --url "https://cpd-rpanamespace.apps.rpa-ocp.cp.fyre.ibm.com/rpa/api/v1.0/" --tenant 5000 --userName carolagirolami --password XXXX -v Detailed
VALID server certificate.
Requested URI: https://cpd-rpanamespace.apps.rpa-ocp.cp.fyre.ibm.com/rpa/api/v1.0/en-US/configuration
Effective date: 4/14/2023 6:54:37 AM
Expiration date: 7/13/2023 6:54:37 AM
Issuer: CN=IBM Automation Foundation CA
Subject: CN=cpd
VALID server certificate.
Requested URI: https://cpd-rpanamespace.apps.rpa-ocp.cp.fyre.ibm.com/rpa/api/v1.0/en-US/account/tenant
Effective date: 4/14/2023 6:54:37 AM
Expiration date: 7/13/2023 6:54:37 AM
Issuer: CN=IBM Automation Foundation CA
Subject: CN=cpd
System.Net.Http.HttpRequestException: The request failed with status BadRequest, reason Bad Request. Details:{"errorMessage":"Model is not valid","modelState":{"userName":["The UserName field is required.","'User Name' must not be empty."]}}

   at Joba.IBM.RPA.Extensions.ThrowWhenUnsuccessful(HttpResponseMessage response, CancellationToken cancellation)
   at Joba.IBM.RPA.Cli.RpaClient.AccountResource.FetchTenantsAsync(String userName, CancellationToken cancellation)
   at Joba.IBM.RPA.Cli.RpaClient.AccountResource.AuthenticateAsync(Int32 tenantCode, String userName, String password, CancellationToken cancellation)
   at Joba.IBM.RPA.AccountCredentials.AuthenticateAsync(IAccountResource resource, CancellationToken cancellation)
   at Joba.IBM.RPA.Proj
C:\Users\Administrator\AppData\Local\Joba\rpa cli>
```

### Expected behavior

The account to access the tenat is carolagirolami.
I have tried with userName = carolagirolami@baw.org but I get the same error.
<img width="1505" alt="image" src="https://github.com/IBM/ibm-rpa-cli/assets/39830828/56c1963b-77f2-4047-9286-73a61f30f34c">

### Version

1.0.0-beta-1 (latest)

### Which operating system?

Windows Server

**Comment by carolagirolami** [comment]
first version

**Comment by carolagirolami** [comment]
1. Operator version is 1.12.0 which correspond to RPA 23.0.4
2.As far as I understand, it is not possible to use RPA on OCP without SSO

**Comment by JobaDiniz** [comment]
As stated in the [documentation](https://ibm.github.io/ibm-rpa-cli/#/faq?id=does-it-support-single-sign-on), RPA CLI needs a **regular** user. It does not support SSO authentication flow.

**Comment by JobaDiniz** [comment]
>As far as I understand, it is not possible to use RPA on OCP without SSO

It seems OCP is not supported **since** you cannot create a **regular user**. Until IBM RPA provides a different method of authentication for environments with SSO, such as api-key, OCP **is not supported**.

**Comment by JobaDiniz** [comment]
@carolagirolami it looks like there's a way to get a `token` **programatically** when SSO is configured: https://www.ibm.com/docs/en/rpa/23.0?topic=openshift-get-access-token-api

It's not well documented. If that works, this is a **new feature** that RPA CLI would have to implement.

**Comment by JobaDiniz** [comment]
@carolagirolami I do not know whether you still want to try out this tool, but I successfully implemented the OCP + SSO support.
Documentation: https://ibm.github.io/ibm-rpa-cli/#/guide/environment?id=red-hat%c2%ae-openshift%c2%ae-support-with-single-sign-on
