### ISSUE TITLE
Not sure how to deploy

### ISSUE THREAD

**Issue by ncrowther** [IBM/ibm-rpa-cli#64]
I've created the config file below, but I cant install a package.  am I missing a step?

**rpa package install NTC_BOT
_No packages were found with the query 'NTC_BOT'. Use 'rpa package install NTC_BOT' to install it first.
 Use 'rpa package' to manage packages._** 

{
  "environments": {
    "prod": {
      "code": 5001,
      "name": "IBM RPA Tech Sales",
      "region": "UK1",
      "address": "https://uk1api.wdgautomation.com/v1.0/"
    },
    "dev": {
      "code": 5001,
      "name": "IBM UK1",
      "region": "UK1",
      "address": "https://uk1api.wdgautomation.com/v1.0/"
    }
  },
  "description": "Test Bot",
  "robots": {
    "testbot": {
      "type": "unattended",
      "timeout": "00:05:00",
      "description": "testbot"
    }
  },
  "packages": {
    "NTC_BOT": "1"
  },
  "parameters": {
    "param1": "test"
  }
}

**Comment by JobaDiniz** [comment]
Did you configure package sources?

https://ibm.github.io/ibm-rpa-cli/#/guide/package-source

**Comment by ncrowther** [comment]
Yes, I used the command _rpa package install testing_

It returns

No packages were found with the query 'testing'. Use 'rpa package install testing' to install it first.

**Comment by JobaDiniz** [comment]
What are you trying to accomplish?
To install packages, you need to configure [package sources](https://ibm.github.io/ibm-rpa-cli/#/guide/package-source) **first**. This will create another file `[project-name].sources.json.

**Comment by JobaDiniz** [comment]
Can you run the command again with `-v Detailed` option?

https://ibm.github.io/ibm-rpa-cli/#/support?id=troubleshooting

**Comment by JobaDiniz** [comment]
> Yeh did that. I am a bit confused about the sequence of events. It would be great to have a tutorial on how to deploy and run your first bot.

I plan to create a sample GitHub repository to show off (#70). But for now, you can follow the sequence for **unattended**:

## [Install](https://ibm.github.io/ibm-rpa-cli/#/guide/getting-started)
## [Create a project](https://ibm.github.io/ibm-rpa-cli/#/guide/project)
`rpa project new MyProject`
## [Create a robot](https://ibm.github.io/ibm-rpa-cli/#/guide/robot)
`rpa bot new MyRobot --template unattended`
## [Manually tweak](https://ibm.github.io/ibm-rpa-cli/#/guide/robot?id=unattended) the `MyProject.rpa.json`
Add a **valid** and **existing** computer group name to the `MyProject.rpa.json` file

```
{
  ...
  "robots": {
    "MyRobot": {
      "type": "unattended",
      ...
      "computer-group": "[computer_group_name]"
    }
  }
}

```
## [Add an environment to deploy to](https://ibm.github.io/ibm-rpa-cli/#/guide/environment)
`rpa env new dev --url [url] --region [region] --tenant [tenant] --username [username] --password [password]`
## Deploy to the environment *(missing doc)*
`rpa deploy dev`

**Comment by ncrowther** [comment]
Got it.  Thanks.  All we need now is for the product (rather than your asset) to have multiple scripts associated to one project.

**Comment by JobaDiniz** [comment]
> Got it.  Thanks.  All we need now is for the product (rather than your asset) to have multiple scripts associated to one project.

Why? You don't need to store the scripts in ibm rpa, store in github, and then deploy the github project (rpa deploy). Why would you store in ibm rpa?
